# Generated by Django 2.0.2 on 2018-03-18 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Titulo')),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(verbose_name='Fecha del Evento')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2018, 3, 18, 17, 10, 18, 648787), verbose_name='Fecha de Publicacion')),
            ],
        ),
    ]
