# Generated by Django 2.0.2 on 2018-03-18 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 18, 17, 10, 49, 265816), verbose_name='Fecha de Publicacion'),
        ),
    ]
