# Generated by Django 2.0.3 on 2018-05-08 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180318_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 8, 11, 24, 47, 237842), verbose_name='Fecha de Publicacion'),
        ),
    ]
