# Generated by Django 2.0.3 on 2018-05-08 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180508_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 8, 11, 52, 3, 126300), verbose_name='Fecha de fin del Evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 8, 11, 52, 3, 126265), verbose_name='Fecha del Evento'),
        ),
    ]
