# Generated by Django 2.0.3 on 2018-05-08 15:14

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180508_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='importante',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 8, 12, 14, 55, 895162), verbose_name='Fecha de fin del Evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 8, 12, 14, 55, 895133), verbose_name='Fecha del Evento'),
        ),
    ]
